# Generated by Django 3.1 on 2020-09-27 14:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 27, 14, 46, 10, 350095)),
        ),
        migrations.AddField(
            model_name='note',
            name='labels',
            field=models.CharField(choices=[('primary', 'primary'), ('success', 'success')], default='success', max_length=50),
        ),
    ]
