# Generated by Django 3.1 on 2020-09-27 14:47

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_auto_20200927_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 27, 14, 47, 8, 331472, tzinfo=utc)),
        ),
    ]
