# Generated by Django 3.1 on 2020-09-27 14:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_auto_20200927_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='due_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
